[2022-01-24 02:06:21,912] {processor.py:163} INFO - Started process (PID=1147) to work on /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:06:21,914] {processor.py:642} INFO - Processing file /opt/airflow/dags/stocks_dag.py for tasks to queue
[2022-01-24 02:06:21,915] {logging_mixin.py:109} INFO - [2022-01-24 02:06:21,915] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:06:23,226] {logging_mixin.py:109} INFO - [2022-01-24 02:06:23,224] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/stocks_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stocks_dag.py", line 10, in <module>
    from get_financials import get_financials
  File "/opt/airflow/dags/get_financials.py", line 5, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2022-01-24 02:06:23,239] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:06:23,248] {processor.py:171} INFO - Processing /opt/airflow/dags/stocks_dag.py took 1.340 seconds
[2022-01-24 02:06:53,767] {processor.py:163} INFO - Started process (PID=1215) to work on /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:06:53,770] {processor.py:642} INFO - Processing file /opt/airflow/dags/stocks_dag.py for tasks to queue
[2022-01-24 02:06:53,771] {logging_mixin.py:109} INFO - [2022-01-24 02:06:53,771] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:06:54,243] {logging_mixin.py:109} INFO - [2022-01-24 02:06:54,240] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/stocks_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stocks_dag.py", line 10, in <module>
    from get_financials import get_financials
  File "/opt/airflow/dags/get_financials.py", line 5, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2022-01-24 02:06:54,253] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:06:54,259] {processor.py:171} INFO - Processing /opt/airflow/dags/stocks_dag.py took 0.497 seconds
[2022-01-24 02:07:24,327] {processor.py:163} INFO - Started process (PID=1274) to work on /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:07:24,329] {processor.py:642} INFO - Processing file /opt/airflow/dags/stocks_dag.py for tasks to queue
[2022-01-24 02:07:24,331] {logging_mixin.py:109} INFO - [2022-01-24 02:07:24,330] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:07:24,744] {logging_mixin.py:109} INFO - [2022-01-24 02:07:24,741] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/stocks_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stocks_dag.py", line 10, in <module>
    from get_financials import get_financials
  File "/opt/airflow/dags/get_financials.py", line 5, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2022-01-24 02:07:24,757] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:07:24,765] {processor.py:171} INFO - Processing /opt/airflow/dags/stocks_dag.py took 0.443 seconds
[2022-01-24 02:07:55,235] {processor.py:163} INFO - Started process (PID=1340) to work on /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:07:55,238] {processor.py:642} INFO - Processing file /opt/airflow/dags/stocks_dag.py for tasks to queue
[2022-01-24 02:07:55,239] {logging_mixin.py:109} INFO - [2022-01-24 02:07:55,239] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:07:55,663] {logging_mixin.py:109} INFO - [2022-01-24 02:07:55,661] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/stocks_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stocks_dag.py", line 10, in <module>
    from get_financials import get_financials
  File "/opt/airflow/dags/get_financials.py", line 5, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2022-01-24 02:07:55,675] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:07:55,683] {processor.py:171} INFO - Processing /opt/airflow/dags/stocks_dag.py took 0.452 seconds
[2022-01-24 02:08:25,915] {processor.py:163} INFO - Started process (PID=1398) to work on /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:08:25,916] {processor.py:642} INFO - Processing file /opt/airflow/dags/stocks_dag.py for tasks to queue
[2022-01-24 02:08:25,918] {logging_mixin.py:109} INFO - [2022-01-24 02:08:25,918] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:08:26,065] {logging_mixin.py:109} INFO - [2022-01-24 02:08:26,064] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/stocks_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stocks_dag.py", line 9, in <module>
    from get_tickers import get_tickers
ImportError: cannot import name 'get_tickers' from 'get_tickers' (/opt/airflow/dags/get_tickers.py)
[2022-01-24 02:08:26,088] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:08:26,098] {processor.py:171} INFO - Processing /opt/airflow/dags/stocks_dag.py took 0.187 seconds
[2022-01-24 02:08:56,165] {processor.py:163} INFO - Started process (PID=1461) to work on /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:08:56,168] {processor.py:642} INFO - Processing file /opt/airflow/dags/stocks_dag.py for tasks to queue
[2022-01-24 02:08:56,169] {logging_mixin.py:109} INFO - [2022-01-24 02:08:56,169] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:08:56,315] {logging_mixin.py:109} INFO - [2022-01-24 02:08:56,313] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/stocks_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stocks_dag.py", line 9, in <module>
    from get_tickers import get_tickers
ImportError: cannot import name 'get_tickers' from 'get_tickers' (/opt/airflow/dags/get_tickers.py)
[2022-01-24 02:08:56,330] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:08:56,338] {processor.py:171} INFO - Processing /opt/airflow/dags/stocks_dag.py took 0.177 seconds
[2022-01-24 02:09:26,674] {processor.py:163} INFO - Started process (PID=1512) to work on /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:09:26,676] {processor.py:642} INFO - Processing file /opt/airflow/dags/stocks_dag.py for tasks to queue
[2022-01-24 02:09:26,677] {logging_mixin.py:109} INFO - [2022-01-24 02:09:26,677] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:09:26,815] {logging_mixin.py:109} INFO - [2022-01-24 02:09:26,813] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/stocks_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stocks_dag.py", line 9, in <module>
    from get_tickers import get_tickers
ImportError: cannot import name 'get_tickers' from 'get_tickers' (/opt/airflow/dags/get_tickers.py)
[2022-01-24 02:09:26,830] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/stocks_dag.py
[2022-01-24 02:09:26,838] {processor.py:171} INFO - Processing /opt/airflow/dags/stocks_dag.py took 0.168 seconds
